# 対象パス
# included:
#   - flutter/ios/Classes/ConvertUtil.swift
#   - flutter/ios/Classes/SwiftThetaClientFlutterPlugin.swift
#   - react-native

custom_rules:
  pirates_beat_ninjas: # rule identifier
    included:
      - ".*\\.swift"

# 除外パス
# excluded:
#   - Tests/SwiftLintFrameworkTests/Resources

# デフォルト有効で無効にするルール
disabled_rules:
  - trailing_whitespace
  - orphaned_doc_comment

# defaultルール以外にopt-inから採用するルール
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes # 「@」付きの属性は、定義と違う行であるべき
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_none_name
  # - discouraged_object_literal # 画像はUIImage()、色はUIColor()を使用すべき
  # - object_literal # 画像は#imageLiteral、色は#colorLiteralを使用すべき
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  # - file_header
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent # 定義が親よりも低いまたは同じアクセス制御レベルを持つようにすべき
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  # - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  # - prefer_self_in_static_references # staticクラス内、自身のstaticメソッドを使用する際、クラス名の代わりにSelfを使用すべき
  - prefer_self_type_over_type_of_self
  # - private_action # @IBAction は private にすべき
  - private_outlet
  # - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - return_value_from_void_function
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  # - strong_iboutlet # @IBOutlet は弱参照で定義すべきではありません
  - test_case_accessibility
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  # - vertical_whitespace_closing_braces # 中括弧を閉じる前に空白行を設けないべき
  # - vertical_whitespace_opening_braces # 中括弧を開く前に空白行を設けないべき
  - xct_specific_matcher
  - yoda_condition

# 変数名制限
identifier_name:
  min_length: # 最少文字数
    warning: 2
    error: 1
  max_length: # 最多文字数
    warning: 50
    error: 100
  excluded: # 除外
    - id
    - x
    - y
    - vc
    - on
    - i

# 1行の文字列制限
line_length:
  - 180 # warning
  - 250 # error

# 型（クラスなど）の行数制限
type_body_length:
  - 400 # warning
  - 600 # error

# 1ファイルの行数制限
file_length:
  - 500 # warning
  - 700 # error

# メソッドの行数制限
function_body_length:
  - 40 # warning
  - 60 # error

# 型（クラスなど）名の制限
type_name:
  min_length: 3
  max_length: 40

# 1メソッドの最大引数数
function_parameter_count:
  - 10 # warning
  - 20 # error
